### ISSUE TITLE
Can't Get Accurate Error Messages When Ptyprocess.exec Failed

### ISSUE THREAD

**Issue by EddyZhou97** [JetBrains/pty4j#101]
I hope to get accurate error messages instead of Unknown reason, when I execute some non-existent commands.
```
java.io.IOException: Exec_tty error:Unknown reason
	at com.pty4j.unix.UnixPtyProcess.execInPty(UnixPtyProcess.java:219) ~[pty4j-0.11.4.jar!/:na]
	at com.pty4j.unix.UnixPtyProcess.<init>(UnixPtyProcess.java:59) ~[pty4j-0.11.4.jar!/:na]
	at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:127) ~[pty4j-0.11.4.jar!/:na]
	at com.pty4j.PtyProcess.exec(PtyProcess.java:91) ~[pty4j-0.11.4.jar!/:na]
	at com.pty4j.PtyProcess.exec(PtyProcess.java:62) ~[pty4j-0.11.4.jar!/:na]
```

**Comment by segrey** [comment]
Thanks, reproduced when command is not in PATH.

**Comment by EddyZhou97** [comment]
It also reproduced when memeory can't allocate in native funcation
![image](https://user-images.githubusercontent.com/36226819/111745680-eb26f380-88c7-11eb-9e10-0bcf778c6952.png)

**Comment by zhaoxini** [comment]
Reason: Not enough storage

Solution ：
1. Increase memory capacity
2. Modify memory strategy （vm.overcommit_memory =1)
3. Check for memory leaks
