### ISSUE TITLE
java.lang.ClassNotFoundException: jtermios.JTermios

### ISSUE THREAD

**Issue by albilu** [JetBrains/pty4j#135]
I am getting this stacktrace while trying to use this library.
Something wrong with JTermios.

Environment:
JDK 11
Linux

pom.xml
`...
<repository>
            <id>jetbrains-intellij-dependencies</id>
            <url>https://packages.jetbrains.team/maven/p/ij/intellij-dependencies</url>
        </repository>
<dependency>
            <groupId>org.jetbrains.pty4j</groupId>
            <artifactId>pty4j</artifactId>
            <version>0.12.10</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.jediterm</groupId>
            <artifactId>jediterm-pty</artifactId>
            <version>2.42</version>
            <type>jar</type>
        </dependency>
...
`

`java.lang.ClassNotFoundException: jtermios.JTermios
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: jtermios.JTermios starting from ModuleCL@2d3f3616[org.netbeans.modules.Python] with possible defining loaders null and declared parents [ModuleCL@2e2f92be[org.openide.loaders], ModuleCL@70c1258b[org.netbeans.modules.editor.lib], ModuleCL@7d3175a0[org.openide.io], org.netbeans.JarClassLoader@26f74281, ModuleCL@2781be77[org.netbeans.modules.editor.indent], org.netbeans.MainImpl$BootClassLoader@7b23ec81, ModuleCL@656ff54[org.netbeans.api.annotations.common], ModuleCL@7a56b64a[org.netbeans.modules.parsing.api], ModuleCL@f12697e[org.netbeans.swing.outline], ModuleCL@1948b399[org.openide.actions], ...40 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
Caused: java.lang.NoClassDefFoundError: jtermios/JTermios
	at com.pty4j.unix.PtyHelpers.<clinit>(PtyHelpers.java:190)
	at com.pty4j.unix.Pty.ptyMasterOpen(Pty.java:137)
	at com.pty4j.unix.Pty.openMaster(Pty.java:173)
	at com.pty4j.unix.Pty.<init>(Pty.java:64)
	at com.pty4j.unix.UnixPtyProcess.<init>(UnixPtyProcess.java:59)
	at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:147)
	at org.netbeans.modules.python.repl.PythonTerminalConnector.createTtyConnector(PythonTerminalConnector.java:77)
	at 
...

Any advice on how to solve this please?

**Comment by albilu** [comment]
Explicitly adding purejavacomm dependency solved the issue
```xml
<dependency>
            <groupId>org.jetbrains.pty4j</groupId>
            <artifactId>purejavacomm</artifactId>
            <version>0.0.11.1</version>
        </dependency>
```
