### ISSUE TITLE
Can not open the terminal on loongarch64

### ISSUE THREAD

**Issue by KatyushaScarlet** [JetBrains/pty4j#142]
I have tried these instructions https://github.com/JetBrains/pty4j/issues/82#issuecomment-607195140, but still can not open the terminal.
Here's the log:
```
katyusha@Katyusha-Laptop-Loongson ~/program/goland/GoLand-2023.2/bin % ./goland.sh
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
2023-08-04 01:06:02,283 [    327]   WARN - #c.i.i.AppStarter - Unable to load JNA library (os=Linux 6.4.1-1, jna.boot.library.path=/home/katyusha/program/goland/GoLand-2023.2/lib/jna/amd64)
java.lang.UnsatisfiedLinkError: Unable to locate JNA native support library
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1018)
        at com.sun.jna.Native.<clinit>(Native.java:221)
        at com.intellij.jna.JnaLoader.load(JnaLoader.java:19)
        at com.intellij.idea.StartupUtil$loadSystemLibsAndLogInfoAndInitMacApp$1$2.invokeSuspend(StartupUtil.kt:366)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-08-04 01:06:03,828 [   1872]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - no such method: sun.font.Font2D.getTypographicFamilyName()String/invokeVirtual
java.lang.NoSuchMethodException: no such method: sun.font.Font2D.getTypographicFamilyName()String/invokeVirtual
        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680)
        at com.intellij.util.MethodHandleUtil.getPublicMethod(MethodHandleUtil.kt:21)
        at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.getFont2dMethod(FontFamilyServiceImpl.java:247)
        at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.<clinit>(FontFamilyServiceImpl.java:45)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
        at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
        at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
        at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
        at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
        at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
        at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1162)
        at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
        at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1146)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NoSuchMethodError: 'java.lang.String sun.font.Font2D.getTypographicFamilyName()'
        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
        ... 33 more
2023-08-04 01:06:03,876 [   1920]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - no such method: sun.font.Font2D.getTypographicSubfamilyName()String/invokeVirtual
java.lang.NoSuchMethodException: no such method: sun.font.Font2D.getTypographicSubfamilyName()String/invokeVirtual
        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680)
        at com.intellij.util.MethodHandleUtil.getPublicMethod(MethodHandleUtil.kt:21)
        at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.getFont2dMethod(FontFamilyServiceImpl.java:247)
        at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.<clinit>(FontFamilyServiceImpl.java:46)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
        at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
        at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
        at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
        at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
        at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
        at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1162)
        at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
        at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1146)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NoSuchMethodError: 'java.lang.String sun.font.Font2D.getTypographicSubfamilyName()'
        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
        ... 33 more
2023-08-04 01:06:03,919 [   1963]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection
2023-08-04 01:06:05,758 [   3802]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Light - old: Light, new Light
Info  | RdCoroutineScope          | 42:DefaultDispatcher-worker-20 | RdCoroutineHost overridden
2023-08-04 01:06:09,491 [   7535]   WARN - #c.i.u.j.JBCefApp - JCefAppConfig.class is not from a JBR module, url: jar:file:/home/katyusha/program/goland/GoLand-2023.2/lib/lib-client.jar!/com/jetbrains/cef/JCefAppConfig.class (Use JBR bundled with the IDE)
2023-08-04 01:06:09,542 [   7586]   WARN - #c.i.o.a.i.ActionUpdater - 333 ms to grab EDT for EnableScreenSharingAction#update@NavBarToolbar (com.jetbrains.rd.platform.codeWithMe.telephony.EnableScreenSharingAction)
2023-08-04 01:06:12,437 [  10481]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 2 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-d5aed4438951-JavaScript-GO-232.8660.185, bundled-gosdk-c0b0f6247a36-19d37c8dbc2a-org.jetbrains.plugins.go.sharedIndexes.bundled-GO-232.8660.185
2023-08-04 01:06:15,474 [  13518]   WARN - #c.i.o.a.i.ActionUpdater - 2119 ms to grab EDT for BackAction#update@MainToolbar (com.intellij.ide.actions.BackAction)
2023-08-04 01:06:28,448 [  26492] SEVERE - #c.i.o.a.i.ApplicationImpl - Could not initialize class com.sun.jna.Native
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35)
        at jtermios.linux.JTermiosImpl.<clinit>(JTermiosImpl.java:61)
        at jtermios.JTermios.<clinit>(JTermios.java:288)
        at com.pty4j.unix.PtyHelpers.<clinit>(PtyHelpers.java:190)
        at com.pty4j.unix.Pty.ptyMasterOpen(Pty.java:130)
        at com.pty4j.unix.Pty.openMaster(Pty.java:166)
        at com.pty4j.unix.Pty.<init>(Pty.java:64)
        at com.pty4j.unix.UnixPtyProcess.<init>(UnixPtyProcess.java:59)
        at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:147)
        at org.jetbrains.plugins.terminal.LocalTerminalDirectRunner.createProcess(LocalTerminalDirectRunner.java:258)
        at org.jetbrains.plugins.terminal.LocalTerminalDirectRunner.createProcess(LocalTerminalDirectRunner.java:56)
        at org.jetbrains.plugins.terminal.AbstractTerminalRunner.lambda$openSessionInDirectory$2(AbstractTerminalRunner.java:216)
        at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to locate JNA native support library [in thread "DefaultDispatcher-worker-22"]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1018)
        at com.sun.jna.Native.<clinit>(Native.java:221)
        at com.intellij.jna.JnaLoader.load(JnaLoader.java:19)
        at com.intellij.idea.StartupUtil$loadSystemLibsAndLogInfoAndInitMacApp$1$2.invokeSuspend(StartupUtil.kt:366)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-08-04 01:06:28,455 [  26499] SEVERE - #c.i.o.a.i.ApplicationImpl - GoLand 2023.2  Build #GO-232.8660.185
2023-08-04 01:06:28,456 [  26500] SEVERE - #c.i.o.a.i.ApplicationImpl - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: N/A
2023-08-04 01:06:28,456 [  26500] SEVERE - #c.i.o.a.i.ApplicationImpl - OS: Linux
```

**Comment by wxpppp** [comment]
@KatyushaScarlet,hi. Due to the presence of architecture-specific libraries in the JNA jar package, if you want to use Goland, you should replace the corresponding jar package in the lib directory with the JNA jar package provided by Loongson. Here is the download link for Loongarch JNA: http://maven.loongnix.cn/loongarchabi1/maven/net/java/dev/jna/jna/. Additionally, if you want to find out which jar packages contain architecture-specific libraries, you can use the following command in the shell: "for file in (find -name "*.jar"); do jar tf(find−name"∗.jar");dojartffile | grep -E "so$" && echo $file; done". I hope this can help you.

**Comment by wxpppp** [comment]
for file in $(find -name "*.jar"); do jar tf $file | grep -E "so\$" && echo $file; done

**Comment by wxpppp** [comment]
`for file in $(find -name "*.jar"); do jar tf $file | grep -E "so\$" && echo $file; done`
