### ISSUE TITLE
How to use it in Android?

### ISSUE THREAD

**Issue by 10cl** [JetBrains/pty4j#81]
so, tell me, How to use it in Android?  help me!

**Comment by 10cl** [comment]
why android load libutil.so
`2019-10-17 11:57:11.233 1738-1738/? I/PtyHelpers: Cannot load implementation of interface com.pty4j.unix.PtyHelpers$OSFacadejava.lang.UnsatisfiedLinkError: Unable to load library 'util': Native library (android-arm/libutil.so) not found in resource path (.)
2019-10-17 11:57:11.236 1738-1738/? I/PtyHelpers: Cannot load native pty executor libraryjava.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/attribute/FileAttribute;
2019-10-17 11:57:11.236 1738-1738/? W/System.err: java.lang.RuntimeException: Cannot load implementation of interface com.pty4j.unix.PtyHelpers$OSFacade
2019-10-17 11:57:11.242 1738-1738/? W/System.err:     at com.pty4j.unix.PtyHelpers.getOsFacade(PtyHelpers.java:247)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.unix.PtyHelpers.getInstance(PtyHelpers.java:262)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.unix.Pty.ptyMasterOpen(Pty.java:140)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.unix.Pty.openMaster(Pty.java:176)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.unix.Pty.<init>(Pty.java:55)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.unix.UnixPtyProcess.<init>(UnixPtyProcess.java:83)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:111)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.PtyProcess.exec(PtyProcess.java:78)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.PtyProcess.exec(PtyProcess.java:45)
2019-10-17 11:57:11.243 1738-1738/? W/System.err:     at com.pty4j.PtyProcess.exec(PtyProcess.java:41)
`
